COPY ~ghostdogs-pst-ui/Main_files~ ~override~
COPY ~ghostdogs-pst-ui/Main_files2~ ~override~
COPY ~ghostdogs-pst-ui/1024_files/1024_MOS~ ~override~
COPY ~ghostdogs-pst-ui/1024_files/1024_CHU~ ~override~

COPY_EXISTING ~CPMOSCP.mos~ ~override~
~CPMOSPPP.mos~ ~override~
~GPMOS5.mos~ ~override~
~WMMOSDP.mos~ ~override~
~WMMOSFM.mos~ ~override~
EXTEND_MOS RIGHT Xnew

COPY_EXISTING ~WMMOS2.mos~ ~override~
EXTEND_MOS RIGHT Xnew - 214